# Generated by Django 3.2 on 2022-11-08 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa_transaction', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма транзакции')),
                ('date_transaction', models.DateField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('time_transaction', models.TimeField(auto_now_add=True, verbose_name='Время транзакции')),
                ('organization', models.CharField(max_length=30, verbose_name='Организация')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_transactions.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Tранзакция',
                'verbose_name_plural': 'Tранзакции',
            },
        ),
    ]
